:icons: font
:experimental: true
= README

== Module

=== app/backend-api

Datenmodell für das Backend.

https://projectlombok.org/

https://github.com/FasterXML/jackson-docs

=== app/backend

REST-API für das Backend.

https://spring.io/projects/spring-framework

https://spring.io/projects/spring-restdocs

https://spring.io/projects/spring-data-jpa

https://spring.io/projects/spring-data-rest

https://docs.liquibase.com/home.html

=== app/server

Spring-Boot-Server mit einer HSQL-Datenbank.

https://spring.io/projects/spring-boot

http://hsqldb.org

=== app/client

Svelte-Client mit TailwindCSS.

https://svelte.dev

https://tailwindcss.com

https://visionmedia.github.io/page.js

https://vitejs.dev

=== app/deploy

Deployment in einem Kubernetes-Cluster.

https://kubernetes.io

https://github.com/kubernetes/kubectl

https://github.com/kubernetes/ingress-nginx

https://helm.sh

== Häufig gestellte Fragen

[[_f1]]
=== Code bauen und testen

[source, gradle]
----
./gradlew clean build
----

[[_f2]]
=== Code formatieren

[source, gradle]
----
./gradlew spotlessApply
----

[[_f3]]
=== Spring-Boot-Server lokal starten

[source, gradle]
----
./gradlew bootRun
----

Der Befehl startet den Server im Vordergrund.
Die Anwendung wird im Browser auf `localhost:8080` aufgerufen.
Der Server muss mit `Ctrl-C` beendet werden.

Mit der Umgebungsvariable `LOGGING_LEVEL_ORG_HIBERNATE_TYPE` kann die Ausgabe von Typinformationen gesteuert werden.
Mit dem Wert `TRACE` werden bspw. die aktuellen Parameter von Statements ausgegeben.

Mit der Umgebungsvariable `LOGGING_LEVEL_ORG_HIBERNATE_STAT` kann die Ausgabe von Statistiken gesteuert werden.
Mit dem Wert `DEBUG` werden bspw. die Kennzahlen von Statements ausgegeben.

[[_f5]]
=== Svelte-Client lokal starten

[source, npm]
----
npm --prefix app/client run dev
----

Der Befehl startet den Client im Vordergrund.
Die Anwendung wird im Browser mit `localhost:5000` aufgerufen.
Der Client muss mit `Ctrl-C` beendet werden.

[[_f6]]
=== Dokumentation lokal bauen

[source, gradle]
----
./gradlew asciidoctor
----

Die Dokumentation befindet sich im `pages`-Ordner.

=== Kubernetes-Cluster lokal einrichten

Siehe https://www.docker.com/products/docker-desktop/

Siehe https://rancherdesktop.io/

=== Kubernetes-Ingress lokal installieren

[source, gradle]
----
./gradlew installIngress
----

Der Ingress-Service wird mit `helm` installiert und gestartet.

=== Kubernetes-Ingress lokal entfernen

[source, gradle]
----
./gradlew uninstallIngress
----

Der Ingress-Service wird mit `helm` gestoppt und entfernt.

=== Kubernetes-Deployment lokal installieren

[source, gradle]
----
./gradlew deploy
----

Docker-Images für die Anwendung werden aktualisiert.
Die Anwendung wird mit `helm` installiert und gestartet.
Sie wird im Browser auf `localhost` aufgerufen.

[source, gradle]
----
./gradlew install
----

Docker-Images für die Anwendung werden *nicht* aktualisiert.
Die Anwendung wird mit `helm` installiert und gestartet.
Sie wird im Browser auf `localhost` aufgerufen.

=== Kubernetes-Deployment lokal entfernen

[source, gradle]
----
./gradlew uninstall
----

Die Anwendung wird mit `helm` gestoppt und entfernt.
