:icons: font
:experimental: true
= Self-Contained System mit Spring-Boot und Svelte-UI

== Projekte

=== app/backend-api

Datenmodell für das Backend.

https://projectlombok.org/

https://github.com/FasterXML/jackson-docs

=== app/backend

REST-API für das Backend.

https://spring.io/projects/spring-framework

https://spring.io/projects/spring-restdocs

https://spring.io/projects/spring-data-jpa

https://spring.io/projects/spring-data-rest

https://docs.liquibase.com/home.html

=== app/server

Spring-Boot-Server der Anwendung mit einer HSQL-Datenbank.

https://spring.io/projects/spring-boot

=== app/client

Svelte-Client der Anwendung.

https://svelte.dev/

https://smeltejs.com/

https://tailwindcss.com/docs

https://visionmedia.github.io/page.js/

=== app/deploy

Deployment der Anwendung.

https://docs.docker.com/desktop/kubernetes/

https://kubernetes.io/docs

https://github.com/kubernetes/kubectl

https://github.com/kubernetes/ingress-nginx

https://github.com/kubernetes/dashboard

https://github.com/helm/helm

https://helm.sh/

== Häufig gestellte Fragen

[[_f1]]
=== Code bauen und testen

----
./gradlew clean build
----

[[_f2]]
=== Code formatieren

----
./gradlew spotlessApply
----

[[_f3]]
=== Spring-Boot-Server lokal starten

----
./gradlew app:server:bootRun
----

Mit der Umgebungsvariable 'LOGGING_LEVEL_ORG_HIBERNATE_TYPE' kann die Ausgabe von Typinformationen gesteuert werden.
Mit dem Wert `TRACE` werden bspw. die aktuellen Parameter von Statements ausgegeben.

Mit der Umgebungsvariable 'LOGGING_LEVEL_ORG_HIBERNATE_STAT' kann die Ausgabe von Statistiken gesteuert werden.
Mit dem Wert `DEBUG` werden bspw. die Kennzahlen von Statements ausgegeben.

[[_f4]]
=== Spring-Boot-Server lokal bauen

----
./gradlew app:server:bootBuildImage
----

Die Umgebungsvariable `CI_REGISTRY_IMAGE` muss gesetzt sein.
Das Docker-Image wird mit
https://buildpacks.io[`buildpacks`]
gebaut.
Bitte auch die 
https://buildpacks.io/docs/reference/reproducibility/[Hinweise zum Zeitstempel]
beachten.

[[_f5]]
=== Svelte-Client lokal starten

----
./gradlew app:client:nodeBuildImage
----

[[_f6]]
=== Dokumentation lokal bauen

----
./gradlew asciidoctor
----

Die Dokumentation befindet sich im `pages`-Ordner.

=== Kubernetes-Cluster lokal einrichten

Mit Docker-Desktop wird der lokale Kubernetes-Cluster eingerichtet.

=== Kubernetes-Ingress lokal einrichten

----
./gradlew deployIngress
----

Der Ingress-Service wird installiert und gestartet.

=== Kubernetes-Dashboard lokal einrichten

----
./gradlew deployDashboard
kubectl proxy
----

Das Dashboard wird mit der angezeigten URL aufgerufen.
Beim ersten Aufruf muss das am Bildschirm angezeigte Token eingegeben werden.
Das Token ist zeitlich befristet.
Nach Ablauf der Gültigkeit muss mit

----
./gradlew createDashboardToken
----

ein neues Token erzeugt und eingegeben werden.

=== Kubernetes-Deployment lokal ausführen

----
./gradlew deployApplication
----

Die Anwendung wird mit `localhost` aufgerufen.
