:restdocDir: ../../../../../../build/generated-snippets
= Nutzer-API

REST-API für die Verwaltung von _Nutzer_-Objekten.

== `POST /api/nutzer`

Die Operation speichert ein neues _Nutzer_-Objekt.

****

.CURL
include::{restdocDir}/post-api-nutzer/curl-request.adoc[]

.Request
include::{restdocDir}/post-api-nutzer/http-request.adoc[]

.Response
include::{restdocDir}/post-api-nutzer/response-body.adoc[]

****

Die Operation meldet `Created` bzw. den Code 201, wenn das Objekt erfolgreich angelegt wurde.

Die Operation meldet `Bad Request` bzw. den Code 400, wenn die Daten nicht verarbeitet wurden.

Die Operation meldet `Conflict` bzw. den Code 409, wenn die Daten bereits existieren.

== `PUT /api/nutzer/{id}`

Die Operation aktualisiert ein existierendes _Nutzer_-Objekt oder erzeugt ein Neues.

****

.CURL
include::{restdocDir}/put-api-nutzer/curl-request.adoc[]

.Request
include::{restdocDir}/put-api-nutzer/http-request.adoc[]

.Response
include::{restdocDir}/put-api-nutzer/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn das Objekt erfolgreich aktualisiert wurde.

Die Operation meldet `Created` bzw. den Code 201, wenn das Objekt erfolgreich angelegt wurde.

Die Operation meldet `Bad Request` bzw. den Code 400, wenn die Daten nicht verarbeitet wurden.

== `GET /api/nutzer`

Die Operation gibt alle gespeicherten _Nutzer_-Objekte zurück.

****

.CURL
include::{restdocDir}/get-api-nutzer/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-nutzer/http-request.adoc[]

.Response
include::{restdocDir}/get-api-nutzer/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

== `GET /api/nutzer/{id}`

Die Operation zeigt ein gespeichertes _Nutzer_-Objekt an.

****

.CURL
include::{restdocDir}/get-api-nutzer-by-id/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-nutzer-by-id/http-request.adoc[]

.Response
include::{restdocDir}/get-api-nutzer-by-id/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.

== `GET /api/nutzer/search/findByMail`

Die Operation sucht ein gespeichertes _Nutzer_-Objekt mit der angegebenen endeutigen E-Mail-Adresse.

****

.CURL
include::{restdocDir}/get-api-nutzer-by-mail/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-nutzer-by-mail/http-request.adoc[]

.Response
include::{restdocDir}/get-api-nutzer-by-mail/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.

== `DELETE /api/nutzer/{id}`

Die Operation löscht ein gespeichertes _Nutzer_-Objekt.

****

.CURL
include::{restdocDir}/delete-api-nutzer/curl-request.adoc[]

.Request
include::{restdocDir}/delete-api-nutzer/http-request.adoc[]

.Response
 Keine

****

Die Operation meldet `No Content` bzw. den Code 204, wenn die Daten gelöscht wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.
