:restdocDir: ../../../../../../build/generated-snippets
= Aufgabe-API

REST-API für die Verwaltung von _Aufgabe_-Objekten.

== `POST /api/aufgabe`

Die Operation speichert ein neues _Aufgabe_-Objekt.

****

.CURL
include::{restdocDir}/post-api-aufgabe/curl-request.adoc[]

.Request
include::{restdocDir}/post-api-aufgabe/http-request.adoc[]

.Response
include::{restdocDir}/post-api-aufgabe/response-body.adoc[]

****

Die Operation meldet `Created` bzw. den Code 201, wenn das Objekt erfolgreich angelegt wurde.

Die Operation meldet `Bad Request` bzw. den Code 400, wenn die Daten nicht verarbeitet wurden.

Die Operation meldet `Conflict` bzw. den Code 409, wenn die Daten bereits existieren.

== `PUT /api/aufgabe/{id}`

Die Operation aktualisiert ein existierendes _Aufgabe_-Objekt oder erzeugt ein Neues.

****

.CURL
include::{restdocDir}/put-api-aufgabe/curl-request.adoc[]

.Request
include::{restdocDir}/put-api-aufgabe/http-request.adoc[]

.Response
include::{restdocDir}/put-api-aufgabe/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn das Objekt erfolgreich aktualisiert wurde.

Die Operation meldet `Created` bzw. den Code 201, wenn das Objekt erfolgreich angelegt wurde.

Die Operation meldet `Bad Request` bzw. den Code 400, wenn die Daten nicht verarbeitet wurden.

== `PUT /api/aufgabe/{id}/projekt`

Die Operation ändert das Projekt im _Aufgabe_-Objekt.

****

.CURL
include::{restdocDir}/put-api-aufgabe-projekt/curl-request.adoc[]

.Request
include::{restdocDir}/put-api-aufgabe-projekt/http-request.adoc[]

.Response
 Keine

****

Die Operation meldet `No content` bzw. den Code 204, wenn das Objekt erfolgreich aktualisiert wurde.

== `GET /api/aufgabe`

Die Operation gibt alle gespeicherten _Aufgabe_-Objekte zurück.

****

.CURL
include::{restdocDir}/get-api-aufgabe/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-aufgabe/http-request.adoc[]

.Response
include::{restdocDir}/get-api-aufgabe/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

== `GET /api/aufgabe/{id}`

Die Operation zeigt ein gespeichertes _Aufgabe_-Objekt an.

****

.CURL
include::{restdocDir}/get-api-aufgabe-by-id/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-aufgabe-by-id/http-request.adoc[]

.Response
include::{restdocDir}/get-api-aufgabe-by-id/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.

== `DELETE /api/aufgabe/{id}`

Die Operation löscht ein gespeichertes _Aufgabe_-Objekt.

****

.CURL
include::{restdocDir}/delete-api-aufgabe/curl-request.adoc[]

.Request
include::{restdocDir}/delete-api-aufgabe/http-request.adoc[]

.Response
 Keine

****

Die Operation meldet `No Content` bzw. den Code 204, wenn die Daten gelöscht wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.
