:restdocDir: ../../../../../../build/generated-snippets
= ProjektValueRestApi

REST-API für die Verwaltung von _Projekt_-Objekten.

== `POST /api/projekt`

Die Operation speichert ein neues _Projekt_-Objekt.

****

.CURL
include::{restdocDir}/post-api-projekt/curl-request.adoc[]

.Request
include::{restdocDir}/post-api-projekt/http-request.adoc[]

.Response
include::{restdocDir}/post-api-projekt/response-body.adoc[]

****

Die Operation meldet `Created` bzw. den Code 201, wenn das Objekt erfolgreich angelegt wurde.

Die Operation meldet `Bad Request` bzw. den Code 400, wenn die Daten nicht verarbeitet wurden.

Die Operation meldet `Conflict` bzw. den Code 409, wenn die Daten bereits existieren.

== `PUT /api/projekt/{id}`

Die Operation aktualisiert ein existierendes _Projekt_-Objekt oder erzeugt ein Neues.

****

.CURL
include::{restdocDir}/put-api-projekt/curl-request.adoc[]

.Request
include::{restdocDir}/put-api-projekt/http-request.adoc[]

.Response
include::{restdocDir}/put-api-projekt/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn das Objekt erfolgreich aktualisiert wurde.

Die Operation meldet `Created` bzw. den Code 201, wenn das Objekt erfolgreich angelegt wurde.

Die Operation meldet `Bad Request` bzw. den Code 400, wenn die Daten nicht verarbeitet wurden.

== `PUT /api/projekt/{id}/besitzer`

Die Operation ändert den Besitzer im _Projekt_-Objekt.

****

.CURL
include::{restdocDir}/put-api-projekt-besitzer/curl-request.adoc[]

.Request
include::{restdocDir}/put-api-projekt-besitzer/http-request.adoc[]

.Response
 Keine

****

Die Operation meldet `No content` bzw. den Code 204, wenn das Objekt erfolgreich aktualisiert wurde.

== `PUT /api/projekt/{id}/allMitglied`

Die Operation ändert die Mitglieder im _Projekt_-Objekt.

****

.CURL
include::{restdocDir}/put-api-projekt-mitglied/curl-request.adoc[]

.Request
include::{restdocDir}/put-api-projekt-mitglied/http-request.adoc[]

.Response
 Keine

****

Die Operation meldet `No content` bzw. den Code 204, wenn das Objekt erfolgreich aktualisiert wurde.

== `GET /api/projekt`

Die Operation gibt alle gespeicherten _Projekt_-Objekte zurück.

****

.CURL
include::{restdocDir}/get-api-projekt/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-projekt/http-request.adoc[]

.Response
include::{restdocDir}/get-api-projekt/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

== `GET /api/projekt/{id}`

Die Operation zeigt ein gespeichertes _Projekt_-Objekt an.

****

.CURL
include::{restdocDir}/get-api-projekt-by-id/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-projekt-by-id/http-request.adoc[]

.Response
include::{restdocDir}/get-api-projekt-by-id/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.

== `GET /api/projekt/search/findByName`

Die Operation sucht ein gespeichertes _Projekt_-Objekt mit dem angegebenen endeutigen Namen.

****

.CURL
include::{restdocDir}/get-api-projekt-by-name/curl-request.adoc[]

.Request
include::{restdocDir}/get-api-projekt-by-name/http-request.adoc[]

.Response
include::{restdocDir}/get-api-projekt-by-name/response-body.adoc[]

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten geladen wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.

== `DELETE /api/projekt/{id}`

Die Operation löscht ein gespeichertes _Projekt_-Objekt.

****

.CURL
include::{restdocDir}/delete-api-projekt/curl-request.adoc[]

.Request
include::{restdocDir}/delete-api-projekt/http-request.adoc[]

.Response
 Keine

****

Die Operation meldet `Ok` bzw. den Code 200, wenn die Daten gelöscht wurden.

Die Operation meldet `Not found` bzw. den Code 404, wenn die Daten nicht existieren.
