:icons: font
= Esy

== Datenmodell

=== Grundlagen

Datenmodellierung spielt eine wichtige Rolle.
Sie ist Grundlage für die REST-Schnittstelle.
Sie bestimmt ganz maßgeblich die Qualität und Robustheit der Schnittstelle.
Es ist daher essenziell für den Erfolg, dass das Domänenmodell sehr gut getestet ist.
_Domain Driven Design_ (im folgenden kurz mit DDD bezeichnet) ist das Konzept, mit dem das Domänenmodell entwickelt wird.
Es ist Ausdruck der gemeinsamen Sprache in dieser Domäne.

NOTE: Siehe
https://thedomaindrivendesign.io/developing-the-ubiquitous-language
für mehr Informationen über die gemeinsame Sprache.

Durch das strategische Design entwickelt sich ein tiefgreifendes Verständnis der Kontextgrenzen (engl. bounded context) im Produkt.
Jede Domäne manifestiert sich in der Struktur der Software.
Die grafische Visualisierung deckt kritische Pfade oder unbeabsichtigte Rückkopplungen auf.
Zu komplexe Abhängigkeiten werden dadurch sichtbar.

NOTE: Siehe
https://thedomaindrivendesign.io/what-is-strategic-design
für mehr Informationen über strategisches Design.

Innerhalb der Kontextgrenzen entstehen im taktischen Design und durch die Realisierung Schritt für Schritt weitere Elemente des DDD:
Value, Entity, Aggregate, Event, Service, Repository oder Module. 
Damit ergibt sich die Möglichkeit der Verknüpfung der Elemente des DDD untereinander und mit den Fachbegriffen aus dem Glossar.

NOTE: Siehe
https://thedomaindrivendesign.io/what-is-tactical-design
für mehr Informationen über taktisches Design.

=== Implementierung

include::../app/backend-api/src/main/java/esy/json/JsonMapper.adoc[leveloffset=+2]

== Konfiguration

Keine

== Server

=== Grundlagen

_Self Contained Systems_ (im Folgenden kurz SCS) ist ein Architektur- und Organisationskonzept.
Es passt sehr gut zur Datenmodellierung mit _Domain Driven Design_ (im Folgenden kurz DDD).

TIP: Siehe
https://scs-architecture.org
für mehr Informationen.

Die Datenhaltung in einem SCS wird durch eine Datenbank realisiert werden.
Diese Datenbank wird ausschließlich von dem SCS genutzt.
Es gibt keinen Zugriff von anderen Systemen auf diese Datenbank.

Die Datenverarbeitung in einem SCS ist Aufgabe eines Spring-Boot-Servers.
Der Server liest Daten über Schnittstellen ein, verarbeitet sie und stellt sie an einer internen REST-Schnittstelle für die Präsentation im Client zur Verfügung.
Die Daten, für die das SCS die Hoheit besitzt, werden an einer externen Schnittstelle für andere SCS bereitgestellt.

=== Implementierung

include::../app/backend-data/src/main/java/esy/rest/JsonJpaRepository.adoc[leveloffset=+2]

include::../app/backend-data/src/main/java/esy/rest/JsonJpaRestController.adoc[leveloffset=+2]

== Konfiguration

=== `endpoint.properties`

Der Dienst nutzt eine zentrale Konfigurationsdatei für Endpunkte.
Sie wird nur beim Start der Anwendung gelesen.

[source,text]
----
include::../app/backend-data/src/main/resources/endpoint.properties[]
----

=== `database.properties`

Der Dienst nutzt eine zentrale Konfigurationsdatei für die Datenbank.
Sie wird nur beim Start der Anwendung gelesen.

[source,text]
----
include::../app/backend-data/src/main/resources/database.properties[]
----

== Client

=== Grundlagen

_Self Contained Systems_ (im Folgenden kurz SCS) ist ein Architektur- und Organisationskonzept.
Es passt sehr gut zur Datenmodellierung mit _Domain Driven Design_ (im Folgenden kurz DDD).

TIP: Siehe
https://scs-architecture.org
für mehr Informationen.

Die Präsentation der Daten in einem SCS ist Aufgabe eines Svelte-Clients.
Der Client liest die Daten aus der internen REST-Schnittstelle des Servers und präsentiert sie in einer Single-Page-Anwendung im Web-Browser.
Nutzer können Daten, für die das SCS die Hoheit besitzt, bearbeiten und speichern.

=== Implementierung

tbd svelte

tbd page

tbd tailwind

== Konfiguration

tbd postcss

tbd dotenv

tbd vite

tbd nginx

== Github

=== Grundlagen

tbd Gradle

tbd Github Repository

tbd Github Actions

tbd Github Pages

=== Implementierung

.github/workflows/build.yml
[source,yaml,options="nowrap"]
----
include::../.github/workflows/build.yml[]
----

== Konfiguration

tbd ghcr.io
