:projectDir: ..
:icons: font
= App

Die Anwendung ist ein _Self Contained System_.

TIP: Siehe
https://scs-architecture.org
für mehr Informationen.

Die Anwendung basiert im Backend auf dem _Spring_-Framework.

TIP: Siehe
https://spring.io/projects
für mehr Informationen.

Die Anwendung nutzt für das Frontend das _Svelte_-Framework.

TIP: Siehe
https://svelte.dev/
für mehr Informationen.

Die Anwendung zeigt an einem nicht trivialen Beispiel den effektiven Einsatz des _Spring_-Frameworks und weiterer Projekte aus den Spring-Universum.

== Model

Das Modell ist so gestaltet, dass die Daten in einer relationalen Datenbank dauerhaft gespeichert werden.
Für die Speicherung in der Datenbank wird `spring-data-jpa` als Abstraktion eingesetzt.

Optional kann jeder gespeicherte Datensatz auch als Datensatz in einem REST-API veröffentlicht werden.
Für die Veröffentlichung der Daten in einem REST-API wird `spring-data-rest` als Abstraktion eingesetzt.

Optional kann jeder gespeicherte Datensatz auch als Nachricht in einem Datenstrom veröffentlicht werden.
Für die Veröffentlichung der Daten in einem Datenstrom wird `spring-cloud-stream` als Abstraktion eingesetzt.

[plantuml,model,png]
----
!pragma graphviz_dot jdot
hide members
show attributes
Version : major:minor
EventValueBase : id, version
AufgabeValue <|-- EventValueBase
AufgabeValue : text
NutzerValue <|-- EventValueBase
NutzerValue : mail
ProjektValue <|-- EventValueBase
ProjektValue : name
----

== UI

Die Anwendung hat eine reaktive browser-basierte Benutzeroberfläche.

== API

include::{projectDir}/app/backend/src/main/java/esy/app/info/VersionRestApi.adoc[leveloffset=+2]

include::{projectDir}/app/backend/src/main/java/esy/app/nutzer/NutzerValueRestApi.adoc[leveloffset=+2]

include::{projectDir}/app/backend/src/main/java/esy/app/plan/ProjektValueRestApi.adoc[leveloffset=+2]

include::{projectDir}/app/backend/src/main/java/esy/app/plan/AufgabeValueRestApi.adoc[leveloffset=+2]

== Konfiguration

Die Anwendung hat eine zentrale Konfigurationsdatei für Endpunkte.
Sie wird nur beim Start der Anwendung gelesen.

.endpoint.properties
[source,text]
----
include::{projectDir}/app/backend/src/main/resources/endpoint.properties[]
----

Die Anwendung hat eine zentrale Konfigurationsdatei für die Datenbank.
Sie wird nur beim Start der Anwendung gelesen.

.database.properties
[source,text]
----
include::{projectDir}/app/backend/src/main/resources/database.properties[]
----
