version: '2.1'
services:
  server:
    image: demoscs/server
    hostname: server
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_JPA_PROPERTIES_HIBERNATE_METADATA_BUILDER_CONTRIBUTOR: esy.db.HyperSQLMetadataBuilderContributor
      SPRING_DATASOURCE_URL: jdbc:hsqldb:mem:db;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: SA
      SPRING_DATASOURCE_PASSWORD:
  client:
    image: demoscs/client
    hostname: client
    ports:
      - "5000:5000"
