application:
  name: demoscs

# https://github.com/kubernetes/ingress-nginx/
# https://github.com/traefik/traefik/
ingress:
  class: traefik
  host: ""

image:
  # Die URL für den Abruf der Docker-Images.
  registry: ghcr.io/cardsplus/demoscs
  # Der Name des Secrets für den Zugriff auf
  # das Repository.
  # Typ ist kubernetes.io/dockerconfigjson.
  secret: ghcr-login
  # Das Tag für den Abruf der Docker-Images.
  tag: latest
  # Der Name des Docker-Images für den Client.
  clientImageName: client
  clientPort: 5000
  clientCpu: "500m"
  clientMemory: "128Mi"
  # Der Name des Docker-Images für den Server.
  serverImageName: server
  serverPort: 8080
  serverCpu: "500m"
  serverMemory: "512Mi"
