# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/checkout
    - name: Set up git
      uses: actions/checkout@v2

    # https://github.com/actions/cache
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          .gradle
          build
          app/backend/build
          app/backend-api/build
          app/server/build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    # https://github.com/actions/setup-java
    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    # https://github.com/gradle/gradle
    - name: Build with Gradle
      env:
        JAVA_OPTS: '-Dorg.gradle.daemon=false'
        GRADLE_USER_HOME: .gradle
      run: |
        chmod +x gradlew 
        ./gradlew eclipse
        ./gradlew build --parallel
        ./gradlew asciidoctor
        ./gradlew jacocoTestReport
